[package]
authors = ["TheZoq2 <frans.skarman@protonmail.com>", "Christian Meusel <christian.meusel@posteo.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "rtt_target_logger"
version = "0.0.0"

[dependencies]
log = "0.4.11"
rtt-target = { version = "0.2.0", features = ["cortex-m"] }
